FROM node:latest

WORKDIR /app/

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install
RUN npm run db:generate
RUN npm run dev

CMD [ "npm", "run","start-user-app" ]